### ISSUE TITLE
SyntaxError running yarn generate & build

### ISSUE THREAD

**Issue by krsdcbl** [PressLabs/particles#2]
Hello, 

I just pulled the package this morning & eager to try it out, but ran into an issue with `yarn generate`:
```
yarn run v1.3.2
$ grunt
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token )
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`yarn generate --force` works though, with warnings.

Running `yarn build` then returns:
```
yarn run v1.3.2
$ webpack --config webpack.prod.js
/mnt/c/xampp/htdocs/particles/webpack.config.js:35
)
^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/xampp/htdocs/particles/webpack.prod.js:4:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Hugely excited about particles though, truly a missing piece!

**Comment by desero** [comment]
Hi, first of all thanks for your kind words. It seems that you are running the command `yarn generate` where there is no `Gruntfile.js`: `Loading "Gruntfile.js" tasks...ERROR`. Can you please double check that. Also, can you provide us with more details about your env: node, yarn versions?

**Comment by krsdcbl** [comment]
Hey, thx for the quick reply!
I'm running yarn 1.3.2 & node 6.13.0 **(on LXSS under Windows 10, Ubuntu 16.04.3)**

I doubled checked on the Gruntfile though and  I'm running the command from the particles directory itself & do have a `Grundfile.js`
<img width="434" alt="particlesbug" src="https://user-images.githubusercontent.com/28997674/36911887-3f00a87a-1e45-11e8-9997-95b668cd1f76.PNG">

**Comment by desero** [comment]
Can you please try apply this patch and let me know if it works:
[es6.patch.zip](https://github.com/PressLabs/particles/files/1776088/es6.patch.zip)

It could be because `Gruntfile.js` is ES6. this solves the problem.

**Comment by krsdcbl** [comment]
Thank you very much! 

not sure if the patch fixes the issue, there's another error thrown: 
```
krsdcbl@DESKTOP-8FQSDOJ:/mnt/c/xampp/htdocs/particles$ patch -b < es6.patch
patching file Gruntfile.js
krsdcbl@DESKTOP-8FQSDOJ:/mnt/c/xampp/htdocs/particles$ yarn generate
yarn run v1.3.2
$ grunt
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module './Gruntfile.es.js'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by desero** [comment]
I think I've managed to reproduce it. when I run:
```
➜  particles git:(master) ✗ docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app node:6.13.0 yarn generate
yarn run v1.3.2
$ grunt
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token export
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I get the same error, but after applying the changes I've sent you, it works but ofcourse it gives error since fontforge is not installed on node image:
```
➜  particles git:(master) ✗ docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app node:6.13.0 yarn generate
yarn run v1.3.2
$ grunt
Running "clean:demo" (clean) task
>> 0 paths cleaned.

Running "clean:fonts" (clean) task
>> 1 path cleaned.

Running "webfont:particles" (webfont) task
fontforge process has unexpectedly closed.
1. Try to run grunt in verbose mode to see fontforge output: grunt --verbose webfont.
2. If stderr maxBuffer exceeded try to increase execMaxBuffer, see https://github.com/sapegin/grunt-webfont#execMaxBuffer.
Warning: fontforge not found. Please install fontforge and all other requirements: https://github.com/sapegin/grunt-webfont#installation Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So basically its a node version issue. Try running a newer version. Let me know if you get it working. I might put the patch in the next release.

**Comment by desero** [comment]
I've published a new release with ES6 support for Grunt. Please use this release.

**Comment by krsdcbl** [comment]
I pulled the latest release & now get the same results as you do, and am able to run `generate` after installing fontforge. Thank you very much for the support, explanations & really quick fix :)

**Comment by krsdcbl** [comment]
oh, one last thing: after upgrading to the newest release I had to `npm install` in the particles directory for `yarn convert` to run - `yarn install` would show all packages as up-to-date before that. (convert did run straight away before updating everything though)

**Comment by desero** [comment]
@krsdcbl check out the latest version. A complete rewrite
